### PR TITLE
Fix deprecations from deprecation-workflow

### PR DESCRIPTION
**Pull request by internets**
Addresses #1370.

**Changes proposed in this pull request:**
- Update ```ember-concurrency```, ```ember-i18n```, ```ember-pouch```, ```ember-simple-auth```, ```ember-sinon-qunit```, ```worker-pouch```
- Replace Ember.Binding calls with Ember.defineProperty calls
- Fix backtracking rerender error in inventory-location-picker.js (caused by replacing Ember.Binding calls)
- Replace stub(obj, meth, stubFn) with stub(obj, meth).callsFake(stubFn) in sinon tests

(note that this does not completely address #1370. #1369 and #1382 must be completed before ```ember-cli-deprecation-workflow can be removed``` and  #1370 can be closed)

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by internets** [comment]
A-ha, I did not run the electron tests. I'll get those passing.

**Comment by stukalin** [comment]
@internets do you need any help with electron tests?

**Comment by internets** [comment]
@stukalin Yes! Sorry for going radio silent for so long, I've been trying to carve out more time to address this. Both this codebase and electron debugging are new to me so it's been time consuming. Want me to catch you on slack to discuss, or do you want to pull and take a stab at it?

P.S. Yes we can remove those deprecation-workflow config entries, commit incoming.

**Comment by stukalin** [comment]
@internets I've found the reason. The `i18n` library contains some incompatible change in the version 5.1. Rolling it back to 5.0 fixed some of the tests. We'll see what Travis says:)

**Comment by internets** [comment]
Interesting! I tried that downgrade and it did not solve the problem using yarn, but it does work with npm. I'll see if I can figure out the difference. Thanks!

**Comment by internets** [comment]
@stukalin So far my investigations show that even with the same installed versions, using yarn to install results in test failures and using npm results test success. I must be missing something! I'll leave it to you whether you want to merge it the way it is. The electron app does not exhibit the bugs indicated by the test failures when installing via yarn, it only happens in the test environment. 

I don't like giving up on things so I'll continue investigating, but I don't know how long it will take me. I can open a second PR when I figure it out if need be.

**Pull request merged**
