### PR TITLE
refactor(patients): Improve date format consistency

### PR DESCRIPTION
**Pull request by merelj**
Fixes https://github.com/HospitalRun/hospitalrun-frontend/issues/2439

**Changes proposed in this pull request:**

- add formatDate helpers
- add tests for formatDate helper
- use formatDate in components, mentioned in the issue (ViewPatientsTable, ImportantPatientInfo)

image

**Newly added dependencies with [Bundlephobia](https://bundlephobia.com/) links:**

- no new dependencies

### CODE REVIEW

**Comment by blestab** [comment]
Thank you @merelj 

Thank you for your contribution; may go ahead and sign the CLA.

**Comment by merelj** [comment]
@blestab
> may go ahead and sign the CLA

sure thing 👌 
`licence/cla` check failed and suggested me to add another email to my profile which I did. But it seems to be stuck now 😕

**Comment by jackcmeyer** [comment]
> @blestab
> 
> > may go ahead and sign the CLA
> 
> sure thing 👌
> `licence/cla` check failed and suggested me to add another email to my profile which I did. But it seems to be stuck now 😕

Could you close the PR and reopen it again? That usually fixes the bot.

**Comment by merelj** [comment]
> Could you close the PR and reopen it again? That usually fixes the bot.

ok, it suddenly just worked 🎉 😄

**Review by blestab — APPROVED** [review]

**Review by jackcmeyer — APPROVED** [review]

**Pull request merged**
