### PR TITLE
Enabled patient search by phone number

### PR DESCRIPTION
**Pull request by douno**
Fixes # .

**Changes proposed in this pull request:**

- Enabled patient search through their phone number.

Currently patient can only be searched with their id, firstname and lastname

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by jglovier** [comment]
@douno thanks for the pull request! To help us keep this project well documented, please complete the body of the pull request per the template provided (i.e. list out a summary of what you are proposing in the pull request, and in the `Fixes # .` line please reference any relevant issues that this pull address. Thanks!

**Comment by tangollama** [comment]
@douno I'd love to see this PR closed out by you completing the documentation process and correcting the CI errors in the branch. It's a worthwhile feature to add to the system. Would you have further time to invest in it?

**Comment by douno** [comment]
@tangollama I have updated the PR message. As for the CI errors, can you point me in the right direction. The change is so minor so minor so I don't understand why there are 11 fails. Cheers

**Comment by jkleinsc** [comment]
@douno thanks for the PR and the update!  The CI errors were caused by an issue with our tests.  I reran the tests and they now pass, so I am going to merge this PR.

**Comment by jglovier** [comment]
@douno fantastic. Thanks for adding this! :tada:

**Pull request merged**
