### PR TITLE
Moving start up scripts to a directory

### PR DESCRIPTION
**Pull request by filipesperandio**
Address #11 

- `npm start | npm build | npm test` commands now point to scripts under `./scripts` directory.
-  `npm start | ./scripts/server` checks if CouchDB is running

### CODE REVIEW

**Comment by jkleinsc** [comment]
Thanks for the PR @filipesperandio !

I am wondering if we make a small change here and that is to have fail on scripts/server exit with 0 vs 1.  The reason why is that right now when couch isn't running you will see the following NPM error:

> Checking CouchDB....CouchDB must be installed and running for the server to start.
Check https://github.com/HospitalRun/hospitalrun-frontend#install
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! hospitalrun@0.9.0 start: `./scripts/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hospitalrun@0.9.0 start script './scripts/server'.
npm ERR! This is most likely a problem with the hospitalrun package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/server
npm ERR! You can get their info via:
npm ERR!     npm owner ls hospitalrun
npm ERR! There is likely additional logging output above.

While this message certainly catches your attention, it might make people think there is something wrong with the code vs couchdb not running.  If the script exits with 0, you still will see the message about CouchDB:

> Checking CouchDB....CouchDB must be installed and running for the server to start.
Check https://github.com/HospitalRun/hospitalrun-frontend#install

**Comment by jkleinsc** [comment]
@tangollama @jglovier See above... would love your feedback as to what error message shows when you try to run the app and couchdb isn't running.

**Comment by filipesperandio** [comment]
If I let it proceed it fails later on anyways:
```
Error: connect ECONNREFUSED 127.0.0.1:5984
    at Object.exports._errnoException (util.js:849:11)
    at exports._exceptionWithHostPort (util.js:872:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
```

But I can go either way...

**Comment by jkleinsc** [comment]
@filipesperandio I'm not saying let it proceed, just to exit with a status of 0 instead a status of 1 which causes NPM to display the error message above.

**Comment by filipesperandio** [comment]
gotcha. pushed.

**Comment by jglovier** [comment]
How about:

> Oops! Looks like CouchDB isn't running. CouchDB must be running before you can run HospitalRun
> For help or more info see https://github.com/HospitalRun/hospitalrun-frontend#install

**Comment by filipesperandio** [comment]
@jglovier Sounds good! I am usually too serious on my warn messages! :)

**Comment by jkleinsc** [comment]
@filipesperandio thanks for making the suggested changes.  I just tested your changes and for some reason npm build doesn't work for me.  I can call `./script/build` and that runs but if I call `npm build` it doesn't do anything.

**Comment by filipesperandio** [comment]
@jkleinsc Is that suppose to work? I think it is not: https://docs.npmjs.com/cli/build
My understanding is that `npm build [directory]` is to build a subdirectory.
`npm start` and `npm test`, though, are aliases for `npm run start` and `npm run test`.
So `npm run build` works.
Am I missing something?

**Comment by jkleinsc** [comment]
@filipesperandio Gah!  My bad!  I was thinking that npm build would directly run ember build, but yes you are right.  I'll merge the PR.

**Comment by jglovier** [comment]
picard-slow-clap

**Pull request closed without merging**
