### PR TITLE
Adjustments to the primary action and delete buttons

### LINKED ISSUE #360: Primary call to action buttons should be right aligned, secondary buttons beside it to the left
**Expected experience:** Primary call to action buttons on forms and other views should be right aligned in the layout, with the primary action to the far right, and the secondary action to it's immediate left.

**Actual experience:** Buttons are left aligned in the layout, and the primary action is on the left, while the secondary is on the right.

**Screenshots (if applicable):**

image

image

image

-

Related to #359

### PR DESCRIPTION
**Pull request by Dooris**
Fixes #360.

**Changes proposed in this pull request:**
- Moved the primary action button to the right
- Fixed the appearance of the delete button in the user listing

### CODE REVIEW

**Comment by jkleinsc** [comment]
Looks good @Dooris! Thanks for the PR!

**Comment by jglovier** [comment]
For visible UI changes, could you please include a screenshot of the change @Dooris?

**Comment by jglovier** [comment]
And thanks for jumping on this one!

**Comment by Dooris** [comment]
The old delete button in the user listing.
old delete button
The new delete button in the user listing.
new delete button

Old one where the primary action button is on the left.
old
Moved the primary action button to the right.
new

**Pull request merged**
