### PR TITLE
Feature/view appointments calendar

### LINKED ISSUE #1767: View appointments in calendar
## Scenario
**AS**

A user with read access to appointments

**I WANT**

The ability to view the appointments in a calendar view on the `/appointments` route.

**SO THAT**

I can have a better idea of the scheduling at my practice.

## Acceptance Criteria
**GIVEN**

Existing appointments and read access to appointments

**WHEN**

I access the `/appointments` tab

**THEN**

I see the appointments in the calendar.

## Related Issues
HospitalRun/hospitalrun#149

### LINKED ISSUE #1772: View Appointment
## Scenario
**AS**

A user with read access to appointments

**I WANT**

The ability to view an appointment

**SO THAT**

I can look at the appointment information

## Acceptance Criteria
**GIVEN**

A user with read access to appointments and an existing an appointment

**WHEN**

I navigate to `/appointments/:id`

**THEN**
I should see the appointment details

## Related Issues
HospitalRun/hospitalrun#149

### PR DESCRIPTION
**Pull request by jackcmeyer**
Fixes #1767 
Fixes #1772 

* adds screen for viewing appointment information
* adds viewing appointments on calendar (this is a very naive implementation because it pull back ALL appointments in the DB since our current calendar component has no callback for "paging" through the calendar". Once this gets implemented, we can have a much more efficient solution by only fetching one "page" at a time)

### CODE REVIEW

**Comment by jackcmeyer** [comment]
@tehKapa TraivsCI is failing an I'm not sure why. It looks like it may have old code or something.

**Comment by tehKapa** [comment]
I try to figure out

**Comment by tehKapa** [comment]
@jackcmeyer I've the same error on my Mac


```
yarn workspace @hospitalrun/frontend run build
yarn workspace v1.21.1
yarn run v1.21.1
$ react-scripts build
Creating an optimized production build...
Failed to compile.

/Users/kapa/Dev/HospitalRun/hospitalrun/packages/frontend/src/scheduling/appointments/AppointmentDetailForm.tsx
TypeScript error in /Users/kapa/Dev/HospitalRun/hospitalrun/packages/frontend/src/scheduling/appointments/AppointmentDetailForm.tsx(32,19):
Type '{ id: string; value: string; placeholder: string | undefined; onChange: (p: Patient[]) => void; onSearch: (query: string) => Promise<Patient[]>; searchAccessor: string; renderMenuItemChildren: (p: Patient) => Element; }' is not assignable to type 'IntrinsicAttributes & Pick<Props, "id" | "onChange" | "placeholder" | "searchAccessor" | "renderMenuItemChildren" | "onSearch"> & Partial<...> & Partial<...>'.
  Property 'value' does not exist on type 'IntrinsicAttributes & Pick<Props, "id" | "onChange" | "placeholder" | "searchAccessor" | "renderMenuItemChildren" | "onSearch"> & Partial<...> & Partial<...>'.  TS2322

    30 |                 <Typeahead
    31 |                   id="patientTypeahead"
  > 32 |                   value={appointment.patientId}
       |                   ^
    33 |                   placeholder={t('scheduling.appointment.patient')}
    34 |                   onChange={(p: Patient[]) => {
    35 |                     onAppointmentChange({ ...appointment, patientId: p[0].id })


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/kapa/.nvm/versions/node/v12.14.0/bin/node
Arguments: /Users/kapa/.nvm/versions/node/v12.14.0/lib/node_modules/yarn/lib/cli.js run build
Directory: /Users/kapa/Dev/HospitalRun/hospitalrun/packages/frontend
Output:
```

**Comment by tehKapa** [comment]
@jackcmeyer fix it! I have wiped out travis' cache and forced the latest version of components..

**Pull request merged**
