### PR TITLE
Fix 1561

### LINKED ISSUE #1561: ember-intl upgrade side effects
**Expected behavior:**
Warning message should have no HTML in it.
**Actual behavior:**
Warning message has HTML in it.

**Steps to reproduce:**
_New Inventory Item Add_
1. Login
2. Click on Inventory Received 
3. Click on add button
4. View the message with HTML in it

OR 
_New Patient Quick Add_
1. Login
2. Click on Medication -> New Request
3. Enter patient name that doesn't exist
4. Fill in other information
5. View error message

**Screenshots (if applicable):**
_New Inventory Item Add_
image

_New Patient Quick Add_
image

**OS and Browser:**
MacOS, Chrome 70, Firefox, Safari

- [x] warning messages which use HTML to render are showing the raw html in the message
- [x] unable to select first lanaguage
- [x] navigation bar items not being translated
- [ ] warnings with Hebrew in the console and some Hebrew messages not rendering
- [x] default to English for missing translations
- [x] different results between missing translations and empty translations
- [x] loss of support of right-to-left languages

### PR DESCRIPTION
**Pull request by jackcmeyer**
Partial Work #1561

**Changes proposed in this pull request:**
- fixes issue with warning messages rendering with raw HTML in the string instead of the formatted text

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by MatthewDorner** [comment]
We also need htmlSafe on the `dashboard.standalone_welcome` in index.hbs.

In some of those translation strings I see the {} is moved to a different position in the string from where it was before, like totalReceived, areYouSureDelete, maybe others. What was the reason for moving those?

**Comment by jackcmeyer** [comment]
@MatthewDorner I've made the changes for the `dashboard.standalone_welcome` message. I've also removed the fixes for the warning messages because I think that I didn't do it right, even though google translate thought it was right. I will let someone who speaks or knows Hebrew make the changes.

**Comment by MatthewDorner** [comment]
The addition of the parameters into the translation strings seemed good, I just wondered why the brackets changed place. It's OK since I noticed something else in the Hebrew file. For example, `incident.messages.incidentCategorySaved`. The translator translated the names of the parameters themselves, which results in the translations not working. And there are several instances of that in the Hebrew file, so we can make an issue to work on all that separately.

**Comment by jackcmeyer** [comment]
They changed location because of the translations of the parameters being translated as well. So adding in the parameters will move the parentheses.

**Comment by MatthewDorner** [comment]
I think I understand. Yeah that sounds difficult.

**Pull request merged**
