### PR TITLE
Admitted list screen

### LINKED ISSUE #349: Admitted list screen for Patients
New route: /patients/admitted

List the patients with a currently open visit (admission).

### PR DESCRIPTION
**Pull request by dswanson**
Add the link to the sidebar and create a admitted patient screen.

fixes #349

### CODE REVIEW

**Comment by tangollama** [comment]
I'm ready to merge this one. @jglovier, are you on board?

**Comment by jglovier** [comment]
@dswanson can you include a screenshot of the UI changes for reference here?

**Comment by dswanson** [comment]
admitted

**Comment by jglovier** [comment]
@dswanson :+1: :shipit:

**Comment by jglovier** [comment]
will-smith-jazzy-jeff-high-five

**Pull request merged**
