### PR TITLE
Bind attr

### PR DESCRIPTION
**Pull request by billybonks**
Replacing `{{bind-attr}}`

the white space commit fixes things like this.
- trailing white spaces 1-x spaces
- adding EOF new lines

screen shot 2015-09-27 at 10 00 38 pm

### CODE REVIEW

**Comment by billybonks** [comment]
No more {{bind-att}} test fails only on phantom? passes in qunit. is there a known configuration issue

**Comment by jkleinsc** [comment]
@billybonks when I test locally, it works, so I am going to merge this PR.  I'm not sure why its not passing in travis.  We are still cleaning up/setting up testing, so maybe its something there.

**Comment by billybonks** [comment]
cool, did you run the tests, using ember test or via the browser?

**Comment by jkleinsc** [comment]
ember test

**Pull request merged**
