### PR TITLE
CSS refactoring

### LINKED ISSUE #134: Temp styles need cleaned up/removed
There's a bunch of temp/misc styles that need put into their correct partials.

### PR DESCRIPTION
**Pull request by jglovier**
Working on some major CSS refactoring. Still scoping out the best way to approach it, but getting the PR going nice and early.

Current plan is to:
- [x] tidy up the structure of the files
  - [x] get the temp styles into the appropriate partials
  - [x] reorganize stylesheets accordingly

I'm not sure yet how much of the above plan belongs in this particular PR. I'll probably merge and start a new PR a few times just to keep things from getting too big in this one PR.

- Fixes #134
- Addresses #794

_EDIT: I've scoped the above list to just a couple things for this PR._

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by billybonks** [comment]
Exciting

**Comment by jglovier** [comment]
Settled on a path forward, and chatted with @jkleinsc a little bit today about all the changes. I'm going to merge this PR with just the structural cleanup of the existing styles, then open another PR for the next step.

**Comment by jglovier** [comment]
@jkleinsc not sure about this failure, but it appears to be blocking [the test from passing](https://travis-ci.org/HospitalRun/hospitalrun-frontend/builds/174674578).

image

Can you point me to what I need to do to resolve?

**Comment by jglovier** [comment]
@jkleinsc false alarm! It appears to have been an intermittent failure. I re-ran the test and it passed. :zap:

**Pull request merged**
