### PR TITLE
Added localization to Inventory Module

### PR DESCRIPTION
**Pull request by nerdkid93**
Fixes [#276](https://github.com/HospitalRun/hospitalrun-frontend/issues/276).

**Changes proposed in this pull request:**
Adds i18n to all pages in inventory module

***Things to keep working on***
* The buttons on the inventory/adjust page are pulling text from the model, which will display English no matter what
* The inventory reports also generate English content in inventory/reports/controller.js

-

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by nerdkid93** [comment]
I'm confused as to why it just failed to build. It seemed to error out when install PhantomJS...

**Comment by jkleinsc** [comment]
@nerdkid93 it looks like app/inventory/edit/template.hbs has not been translated.

**Comment by jkleinsc** [comment]
@nerdkid93 also, what do you mean by the reports generate english content?  What is it that can't be localized?

**Comment by nerdkid93** [comment]
@jkleinsc Thanks for pointing out edit's template.hbs. That was one of the files I lost when I my github index was corrupted.

**Comment by nerdkid93** [comment]
@jkleinsc As for the english content in the reports, there are a bunch of statements like this: `this._addTotalsRow(`Total for ${parentLocation}: `, locationCost, parentCount);`. I don't know if you want to try to translate each line or find another way to show translated labels for those rows. translations.js already has around 150 lines for the inventory module.

**Comment by jkleinsc** [comment]
@nerdkid93 Can you add the translation of the report text?  It looks like there are only a couple that are needed: Total for {substitute here}: and Subtotal for {substitute text here}:, and Total:

**Pull request closed without merging**
