### PR TITLE
Button Colour Fixed

### LINKED ISSUE #972: [TRACKING ISSUE] Color contrast problems in the UI
**Expected behavior:**
All text in the UI should pass at least [WCAG AA](https://www.w3.org/WAI/WCAG20/quickref/) contrast accessibility. A simple test of text-color on background color on [this color accessibility calculator](http://webaim.org/resources/contrastchecker/) will tell whether any existing pairing of font on background passes. Many of our instances do, and a few do not.

**Actual behavior:**
Currently, there are a number of areas that need to improve to meet AA standard.
Including:
- [ ] _[add checklist of instances to address here]_

**Screenshots (if applicable):**

Some offenders:

---

image

---

image

---

image

---

**How to solve with tooling:**

Some ways we can address this going forward are with tooling.
- [ ] Establish a pattern library and styleguide that removes the possibility of introducing any new failing color styles
- [ ] Add a test for contrast (will need to research options more)

### PR DESCRIPTION
**Pull request by Anisha1234**
Addresses #972 #359 

**Changes proposed in this pull request:**
- background of edit button is changed to #3e95ff and colour changed to #fff ($white)
- new class "btn-extra" added for button "bar-code","checkout".
- btn-extra class in active state has background colour #799fd2 and colour $white and on hover background colour changes to #4a7ec3.
- btn-primary class is added in appropriate places to give similar looks to all the "add" and "update" buttons

appointment-list before:
appointmentlist

appointment-list after:
appointmentlist

custom-form page before:
customform

custorn-form page after:
customform

report-generate page before:
generalreport png

report-generate page after:
generatereport

inventory-list page before:
inventoryitem

inventory-list page after:
inventoryitem

patient-list page before:
patientlist

patient-list page after:
patientlist

@jkleinsc @jglovier @tangollama

### CODE REVIEW

**Comment by jkleinsc** [comment]
@Anisha1234 looks good to me.

@jglovier can you look at this and give your feedback?

**Comment by Anisha1234** [comment]
@jglovier @jkleinsc Do I need to do some changes over here ?

**Comment by jglovier** [comment]
@jkleinsc @Anisha1234 sorry for the delay. I'll review as soon as possible, but will need a day or two to get back to this due to current workload. :heart:

**Comment by tangollama** [comment]
@Anisha1234 any progress?

**Comment by Anisha1234** [comment]
@tangollama I have been busy with some school stuff, with semester exams approaching next week... I was unable to devote adequate time to the project currently. But I will create a pull request in next two days resolving this issue..

**Comment by Anisha1234** [comment]
@jglovier @tangollama @jkleinsc as mentioned I have made changes to keep the button colors to just three variants and I have also set the discharge/checkout button to same width.
Yes, as for buttons being a dominant visual element on addition of multiple rows , I agree with that . And my suggestion on this topic would be addition of meaningful icons as they aren't that distracting and serve the purpose at the same time.

**Comment by tangollama** [comment]
@jglovier I believe your requested changes have been satisfied. I think we should merge this into master. Any objections?

cc: @jkleinsc

**Comment by jglovier** [comment]
@Anisha1234 thanks again for all of your effort on this one!! :zap: :heart: :zap:

**Pull request merged**
