### PR TITLE
Create a script to generate dummy data

### LINKED ISSUE #2122: Create a script to generate dummy data
## 🚀 Feature Proposal
Create a script to generate dummy data. Please note that its loading into the database will be implemented separately.

~~In the Account dropdown menu (located in the Navbar, at far right), create two menu items:~~
~~1. Log in as Test (Clicking on this will load pre-populated dummy data)~~
~~2. Log out (Clicking on this will reset data)~~

## Motivation
- It'll allow us to see the product from users' perspective
- Easier to test features that display data

### PR DESCRIPTION
**Pull request by blestab**
Fixes #2122 .

**Changes proposed in this pull request:**

- Add mocker-data-generator plugin for dummy data generation
- Add a new script into _./util_ that uses the **mocker-data-generator** plugin to create dummy data
NB: script name: _generatePatients_, accepts one argument i.e. number of patients records to generate

**Newly added dependencies with [Bundlephobia](https://bundlephobia.com/) links:**

- https://bundlephobia.com/result?p=mocker-data-generator@2.8.0

### CODE REVIEW

**Comment by blestab** [comment]
Hi @kumikokashii 

When you have a moment may you have a peekat this draft PR and let me know if i am on the right track with my approach. 

Instead of having hardcoded JSON documents with dummy data, i have employed the use of mocker-data-generator (https://bundlephobia.com/result?p=mocker-data-generator@2.8.0) and defined the relevant models to drive the data generation.

**Still to do/figure out:**
I haven't written tests yet and also still have issues with the dummy data generation whereby i ask for say 5 patients, but currently I always end up with less than 5 patients in the repository. At first i though i wasn't detecting correctly when the last patient has been added to the repository before navigating to the patients listing route, but when i temporarily disabled the rerouting, i am still not getting all 5 dummy patients to be saved into the local repository.

**Comment by kumikokashii** [comment]
@blestab Hello! Thank you for reaching out. I have an update.There's been a recent development in creating a more official login/logout

**Comment by kumikokashii** [comment]
@blestab Hello! Thank you for reaching out. I have an update.

1. There's been a recent development in adding a more official login system at the entry to the site. So we no longer need to add a temporary login/logout feature from the Account navbar item.

2. There's still a need for dummy data. I suggest that a script will be created so that we will be able to think about how to utilize the generated data later.

**Comment by blestab** [comment]
Okay great, thanks @kumikokashii 

I will go ahead remove UI and state update related changes and only leave the dummy data generation which other components could then make use of the dummy data in any way desired? The generated data will be of the following form:

`

             {
                  patients:[array of Patients],
                  allergies: [array of Allergies],
                  appointments: [array of Appointments]
                  diagnoses:[array of Diagnoses],
                  notes: [array of Notes],
                  carePlans: [array of CarePlans],
                  relatedPersons: [array of RelatedPersons]
              }
`

If the above sounds about right then maybe we can go ahead update the task description to reflect that we are only focusing on generating dummy data?

**Comment by kumikokashii** [comment]
> If the above sounds about right then maybe we can go ahead update the task description to reflect that we are only focusing on generating dummy data?

@blestab Sounds great. Updated https://github.com/HospitalRun/hospitalrun-frontend/issues/2122. Thank you 👍

**Comment by blestab** [comment]
Hi @kumikokashii 

I have applied the changes as discussed and updated the PR description to indicate the same. For an example of how to use this script, see the unit tests added for this.

Let me know what you think.

**Comment by blestab** [comment]
> 
> 
> I like the script! I think that we should/can take it one step further and enter this in CouchDB.
> 
> We can use CouchDB's REST API to enter documents into the database.
> 
> See: https://www.tutorialspoint.com/couchdb/couchdb_creating_a_document.htm for a nice example on how to create a document.

Great! thanks Jack. Should i go ahead and implement this next step yet or do we want to flesh it out a bit more? 

> We'll need to make sure that the patient that is generated from the mock generator matches the object schema created from the frontend.

Yes. So we have setup the mock-data-generator models based on the respective models (Patient, Appointment, Note, Diagnosis, Allergy, CarePlan and RelatedPerson) from the ./models folder.
_NB: The script doesn't generate Labs or Incidents yet but we can easily add these in if desired._

**Comment by fox1t** [comment]
Hi. I am not sure that this is the correct place for mocking data. If we are going to mock CouchDB we need to add it to server repository. 

This is the correct moment to reorganize our stuff since soon the server part will be mandatory in order to work on FE repo.

**Comment by kumikokashii** [comment]
@blestab It's an awesome script! Great job 👍, and thank you 😊! We'll take it from here. The reason is that we are currently in a beginning phase with the database-related functionalities, and this is a good time to pause before changing this around further.

@fox1t @jackcmeyer A [ticket](https://github.com/HospitalRun/hospitalrun-server/issues/322) has been created to properly place this script in the server repo once ready. This assumes this PR will be merged.

**Comment by blestab** [comment]
Awesome! Thanks Kumiko

**Comment by fox1t** [comment]
@kumikokashii perfect! 
@blestab thanks for your contribution!

**Comment by fox1t** [comment]
@jackcmeyer can we merge this?

**Comment by blestab** [comment]
> 
> 
> @kumikokashii perfect!
> @blestab thanks for your contribution!

My pleasure, looking forward to contribute more now that i have a better understanding of the solution.

**Pull request closed without merging**
