### PR TITLE
Fix issue #380: cascading delete for patient records; delete related records first and then patient record

### LINKED ISSUE #380: Cascading delete for patient record
When deleting a patient, we need to delete all visits, invoices, etc.

### PR DESCRIPTION
**Pull request by aboma**
Fixes #380 Cascading Delete for patient records.

**Changes proposed in this pull request:**
- Delete visits, invoices, and most associated records when deleting patient. Delete these records before deleting patient record to avoid missing records errors.
- Add view to return invoices for patient.

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by jglovier** [comment]
@aboma thanks for the PR. :tada:

>Add view to return invoices for patient.

Can you please add a screenshots to the view you added?

**Comment by jkleinsc** [comment]
@jglovier the view is a database view, not a screen, so I don't think we need a screenshot here.

**Comment by aboma** [comment]
There is no change to the UI in these commits; the view referenced is a Pouch DB view.

**Comment by aboma** [comment]
To test this, find or setup a patient record with invoices, visits and labs associated to him/her. Delete the patient using the delete button. Go to the labs view and verify labs are deleted for selected patient and no error occurs on labs list page. Go to invoices list page and verify invoices are deleted for selected patient and no error occurs on invoices list page.

**Comment by jkleinsc** [comment]
@aboma good work here.  I did notice that there are some orphan records that get left behind because they are children records that don't get directly deleted.    Specifically:
1) appointments
2) billing-line-item (child of invoice)
3) line-item-detail (child of billing-line-item)
4) payment (child of patient and invoice)
5) proc-charge (child of imaging, lab, procedure, and visit)

A couple of other observations:
1. It appears if there are no invoices for a patient, the patient doesn't delete properly.
2. The deletion process takes a little while, so I am wondering if we should leave the modal up until deletion is complete or display a progress modal until the deletion is complete.  The progress modal is in the progress-dialog mixin (app/mixins/progress-dialog).  To use the progress dialog, you would do the following:
1. Include the mixin in your controller
2. define an attribute called progressMessage in your controller which has the message to display while the progress dialog is displayed.
3.  define an attribute called progressTitle in your controller which has the title to display while the progress dialog is displayed.
4. call showProgressModal to display the progress modal
5. call closeProgressModal to close the progress modal once processing is complete.

**Comment by aboma** [comment]
I will add the progress modal (definitely need this) and delete the additional records.

**Comment by jkleinsc** [comment]
Marking as in progress until this PR is complete.

**Comment by aboma** [comment]
I have made the suggested changes. It is now deleting patient appointments, billing line items, payments and proc charges. I have also added a progress modal. 

This pull request should be complete.

**Comment by tangollama** [comment]
@aboma thanks for all the good work on this. It appears that there's one test failing on this branch related to the patient-appointments mixin. See below.

If you'd prefer that I or someone else address this fix, I'm happy to do that. If you want to make this change, we should be able to officially "pass" the build. 

`requireSemicolons: Missing semicolon after statement at mixins/patient-appointments.js :
    12 |      },
    13 |      mapReduce: 'appointments_by_patient'
    14 |    })
--------------^
    15 |  }
    16 |});`

cc: @jkleinsc for any further feedback / review.

**Comment by aboma** [comment]
I fixed this and also added some changes I mistakenly forgot to check-in. Tests are passing now.

**Comment by jkleinsc** [comment]
Thanks @aboma !  Looks good, but I want to test it locally before merging, so I hope to do that tomorrow.

**Comment by jkleinsc** [comment]
@aboma in testing this locally, it appears that if I have a payment on a invoice, the delete errors out with: "ember.debug.js:32110 Error: Attempted to handle event `didSetProperty` on <hospitalrun@model:invoice::ember2049:inv00001> while in state root.deleted.inFlight. Called with {name: paidTotal, oldValue: 12, originalValue: 12, value: 0}." 

Also when I don't have a payment the following child records don't appear to delete: 
1) billing-line-item (child of invoice)
2) line-item-detail (child of billing-line-item)
3) payment (child of patient and invoice)
4) proc-charge (child of imaging, lab, procedure, and visit)

**Comment by aboma** [comment]
Ok, I will review again and fix.

Also, you may want to consider creating a service that wraps the store and enforces data integrity. If all model saving/update/deletes are made through the service then it will prevent data corruption.

**Comment by jkleinsc** [comment]
@aboma I am going to merge in your changes and adapt them to work with changes I made for #381.  Thanks for your work on this PR!

**Pull request merged**
