### PR TITLE
[TRANSLATION] Translated appointments section

### PR DESCRIPTION
**Pull request by mellisdesigns**
Appointments Section Translation

### CODE REVIEW

**Comment by billybonks** [comment]
i think the error is `appointments/today/route.js: line 2, col 8, 'AbstractModuleRoute' is defined but never used.`

**Comment by mellisdesigns** [comment]
@billybonks : fixed the error mentioned above and found a missing translation as well! :dancer:

**Comment by billybonks** [comment]
:+1:

**Comment by jkleinsc** [comment]
Looks good!  Thanks @mellisdesigns and @billybonks.

Closes #275

**Pull request merged**
