### PR TITLE
Prevent all robots from scanning the site

### PR DESCRIPTION
**Pull request by mitchellcash**
- Add a comment making it clear to everyone that the directives from the robots.txt file allow all content on the site to be crawled

### CODE REVIEW

**Comment by jkleinsc** [comment]
@mitchellcash thanks for this PR.  You have brought attention to something I wasn't thinking about.  HospitalRun sites really shouldn't be crawlable by robots because the content isn't intended for public consumption.  Would you be willing to change this PR to implement a robots.txt that denies all robots?

**Comment by mitchellcash** [comment]
I was thinking that but being new to the project I was still trying to learn my way around. I will implement a change like you mention above.

**Comment by mitchellcash** [comment]
@jkleinsc please see the updated commit

**Comment by jkleinsc** [comment]
Looks good.  Thanks @mitchellcash!

**Pull request merged**
