### PR TITLE
fix(shared): pouchdb auth popup

### LINKED ISSUE #2256: Fix basic auth popup happening during login process
## 🐛 Bug Report
Sometimes a basic auth popup happens during the login process

## To Reproduce
Not clear what steps are to reproduce this issue. 

## Expected behavior
The system should use our login page rather than the ugly dialog popup to start the authentication process.

## Technical Notes
- https://docs.couchdb.org/en/stable/intro/security.html
- Library we use for pouchdb authentication: https://github.com/pouchdb-community/pouchdb-authentication

I think that it is likely related to the `skip_setup` flags not being configured properly.

### PR DESCRIPTION
**Pull request by blestab**
Fixes #2256 

**Changes proposed in this pull request:**

- Add skip_setup flag to PouchDB instances creation
- Update couchdb docker local.ini httpd section
- Update nginx.conf 

**Newly added dependencies with [Bundlephobia](https://bundlephobia.com/) links:**

NONE

### CODE REVIEW

**Comment by morrme** [comment]
Hi @blestab , When using a fresh browser, I still see the popup: 

popup

**Comment by jackcmeyer** [comment]
@blestab and @morrme can confirm I also get the issue.

**Comment by blestab** [comment]
Thank you both, i'll try see what else i could be missing

**Comment by jackcmeyer** [comment]
@blestab still getting the issue with Chrome & Incognito

**Comment by morrme** [comment]
Still getting it too, new browser/private tab

**Comment by blestab** [comment]
Thanks @jackcmeyer @morrme, I think now i need to understand how the vercel/staging/live environments are built i.e. whether the nginx/couchdb config info is actually being used at all to build these environments.

**Comment by blestab** [comment]
@morrme @jackcmeyer 

@tehKapa helped me update the couchDB config based on the ini changes in this PR. May you test for me if the popup is still coming up for you,  I want to determine if we maybe need to force a rebuild of the vercel deployment.

**Review by tehKapa — APPROVED** [review]

**Comment by morrme** [comment]
NO popup for me! 🎊

**Review by morrme — APPROVED** [review]

**Pull request merged**
