### PR TITLE
Added i18n error messages on login page

### PR DESCRIPTION
**Pull request by nerdkid93**
Instead of displaying error message from Pouch when login fails, it displays an error message in translations.js.

### CODE REVIEW

**Comment by nerdkid93** [comment]
The error is in the test. Part of this commit is changing the error message when a user fails to login. The actual output should be the expected output.

**Comment by jkleinsc** [comment]
@nerdkid93 Can you update the failing test as part of this PR?
The failing test is located here:
https://github.com/HospitalRun/hospitalrun-frontend/blob/master/tests/acceptance/login-test.js

**Comment by nerdkid93** [comment]
Yup, I'll take care of that tonight.

**Comment by nerdkid93** [comment]
Test has been updated, and all tests were passed.

**Comment by jkleinsc** [comment]
@nerdkid93 looks good. I'll merge it in.  Thanks for the PR!

**Pull request closed without merging**
