### PR TITLE
Updating sortable columns to have sorting icon and updated cursor

### LINKED ISSUE #328: Need Indicator for Sortable Columns
On the /inventory/listing page, there are a bunch of sortable columns to view the inventory and sort accordingly. However, prior to clicking on the column header, there is no indication that you can sort the column. Even on mouse over, the cursor is the text-selector and not the link-clicker. Before sorting After sorting

I would recommend adding an icon like [fa-sort](http://fortawesome.github.io/Font-Awesome/icon/sort/) as part of each sortable-column. Other sorting icons can be found [here](http://fortawesome.github.io/Font-Awesome/icons/) and searching with "sort" as the search phrase.

### PR DESCRIPTION
**Pull request by pete-the-pete**
Fixes #328 

**Changes proposed in this pull request:**
- add new icon for default state of sortable-column
- add 'sortable-column' classname to sortable-column component
- add a new css rule to use the pointer cursor for .sortable-column class

sorting icons

### CODE REVIEW

**Comment by jglovier** [comment]
cc @HospitalRun/core-maintainers

**Comment by jglovier** [comment]
@pete-the-pete thanks for getting started on this! Only design feedback I have at the moment is we should probably reduce the size of the icons a bit, and instead of the double arrows, lets use a single triangle everywhere of [this style](https://octicons.github.com/icon/triangle-down/). To differentiate between active filtering and non-active, lets take a queue from existing patterns and make the triangle color lighter on the non-active filters, and darker on active filters.

**Comment by jglovier** [comment]
If you'd like visual help beyond my written description above, I can post a design comp when I have some time in the next few days.

**Comment by pete-the-pete** [comment]
I can take a look tomorrow and post an update.

**Comment by pete-the-pete** [comment]
I updated to use the arrows and lighter color, but I am seeing this issue, https://github.com/stylelint/stylelint/issues/1513

**Comment by jkleinsc** [comment]
@pete-the-pete looks good to me.  @jglovier what do you think:

screen shot 2016-07-11 at 2 51 16 pm

**Comment by jglovier** [comment]
The new icons looks good, except I think we should only display the active arrow, and hide the others until you hover over it's associated column heading.

**Comment by jkleinsc** [comment]
@jglovier if you look the issue this PR is tied to, #328, it seems the issue is discoverability.  If we don't show any icons, how will users know they can search?

**Comment by jkleinsc** [comment]
@jglovier ping... what do you think?  I would like to move this PR along.

**Comment by jglovier** [comment]
@jkleinsc, sorry, to be more clear I think by default we should always show an icon for the currently active sorted column. So there is always one sorting icon visible.

Also, I'm not too concerned about discoverability because this is a feature most users will probably assume is there already. Sorting tabular data by column is more of an expected behavior than a novel feature we need to explicitly reveal.

**Comment by jkleinsc** [comment]
I am merging this PR as is.  We can cleanup when the icons show as another issue.

**Pull request merged**
