### PR TITLE
fix(lab): In New lab request make the visit field required

### LINKED ISSUE #2551: Lab - In the Request Lab routine make the visit field required
## 🐛 Bug Report

When **Request Lab** for a patient without any visit, it will crash.

## To Reproduce

1. Create an patient without adding a visit
2. Click **Request Lab**, input the patient field, leave the visit field blank since it is not required.
3. Notice the crash/error (see screenshot in comments)

## Expected behavior

Request Lab should behave similar to **New Imaging Request** i.e. make the visit field required

## Technical Details

Make the visit field required (as in Imaging Request)

## Your Environment

- *node version*: 12
- *os*: Windows

### PR DESCRIPTION
**Pull request by SamuelQZQ**
Fixes #2551 .

**Changes proposed in this pull request:**

- I make the `NewLabRequest` use the exact same method to solve the `null` visit issue. [`NewImagingRequest.tsx` line65](https://github.com/HospitalRun/hospitalrun-frontend/blob/45647d3b4a15ca8d9c57ebda66b3712658d62f19/src/imagings/requests/NewImagingRequest.tsx#L65)
- My concern is, we use the `as Option[]` at line 57. So that the type of the variable `visits` is not right. It should be `Option[] | null`. Maybe we should do some refactor in `NewImagingRequest.tsx` and `NewLabRequest.tsx` to fix this wrong type. Otherwise, it may lead to other bugs in the future.

### CODE REVIEW

**Comment by tehKapa** [comment]
Could you please sign our CLA? Thank you https://cla.js.foundation/HospitalRun/hospitalrun-frontend?pullRequest=2552

**Comment by SamuelQZQ** [comment]
I have signed the CLA

**Review by blestab — CHANGES_REQUESTED** [review]
>
>I have opened a new session in another chrome instance and I can see the visit option, which is not required, which i guess if why this bug occurs. So if you make the visit required then the issue should be resolved.



Looking good @SamuelQZQ I can see we are no longer crashing if there is no visit specified, however since the visit is required for each lab request we need to make the visit field required as it is on the imaging request.

image

image

**Review by blestab — COMMENTED** [review]
Thanks @SamuelQZQ 

This is now behaving the same as the Request Imaging. I did notice however that Request Imaging (like this latest change) does not prevent saving when visit is not selected, even though it shows visit as required. 

Will create separate issues for these though unless you want to deal with the Lab issue in this PR?

image

**Comment by chadian** [comment]
This somewhat relates to my PR #2555 to make sure `visits` is an empty array when a patient is created. This would help with the "crashing" part but doesn't change the fact if it should be a required field or not (what is covered in this PR).

**Comment by SamuelQZQ** [comment]
@blestab I prefer to work on it in a separate issue. Let's complete this one. I will test more carefully in future work.

**Comment by blestab** [comment]
> @blestab I prefer to work on it in a separate issue. Let's complete this one. I will test more carefully in future work.

Awesome! thanks @SamuelQZQ 

@tehKapa this one now looks good.

**Review by blestab — APPROVED** [review]

**Comment by blestab** [comment]
> This somewhat relates to my PR #2555 to make sure `visits` is an empty array when a patient is created. This would help with the "crashing" part but doesn't change the fact if it should be a required field or not (what is covered in this PR).

Yeah just noticed that. I have since created a separate issue for enforcing the 'required visit' behavior

**Pull request merged**
