### PR TITLE
Remove deprecations in patients

### PR DESCRIPTION
**Pull request by zinyando**
PR already merged in main repo.

### CODE REVIEW

**Comment by billybonks** [comment]
i don't see how this is already merged into master ?

**Comment by billybonks** [comment]
related to this ? https://github.com/HospitalRun/hospitalrun-frontend/commit/02964297925d52d6fe3c1f4dae2b58a4be40fb21

**Comment by zinyando** [comment]
Sorry my mistake, I shouldn't have opened this pull request since the code was merged. It should be closed.

**Comment by billybonks** [comment]
cool

**Pull request closed without merging**
