### PR TITLE
Fixes Issues 590, 591, 592

### PR DESCRIPTION
**Pull request by dapierce**
Fixes
* #590 
* #591 
* #592 

Changes proposed in this pull request:
* The start of changing Translation keys from _ standard to camel case to work with JavaScript convention.

Additionally, this PR also fixes a problem I noticed while testing the invoice--previously the print style did not fix the left margin for the printed invoice, so I have added a fix for the invoice in _print.scss

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by billybonks** [comment]
Hey David thanks :) looks awesome can you add screen shots for the change you made to the printed invoice 👍 

@jkleinsc besides the css i think as long as these commits pass tests it's good to go  since we have the missing translation explosion.

**Comment by dapierce** [comment]
I'll make a screenshot later today for the print invoice.

**Comment by billybonks** [comment]
if you also have the bandwidth, changing the keys in the other translation files would help.

**Comment by dapierce** [comment]
Here's the invoice printing with the improved stylesheet:

invoice print screenshot

I realized that the invoice uses a different class (panel-primary) for its div than the other pages in HospitalRun, so I added it to the print style positioning.

**Comment by jkleinsc** [comment]
Looks good to me.  Thanks @dapierce for the PR!

**Pull request merged**
