### PR TITLE
WIP: feat(sidebar): strip sidebar collapse functionality to user level

### PR DESCRIPTION
**Pull request by Elveskevtar**
Signed-off-by: Kevin Tarta <kevtar@gmail.com>
Adds feature #2098.

**Changes proposed in this pull request:**

- Strip out sidebar collapsing and place functionality in user-slice
- Enable changing the metadata for auth user in couchdb (new sidebar field)
- Enable fetching the new metadata when loading the sidebar (this adds persistence of the state across sessions/devices/etc)

**Newly added dependencies with [Bundlephobia](https://bundlephobia.com/) links:**

N/A

### CODE REVIEW

**Comment by tehKapa** [comment]
Hi @Elveskevtar, can you sign our CLA and resolve conflicts? Thanks

**Comment by fox1t** [comment]
After resolution and sign LGTM. :)

**Comment by tehKapa** [comment]
@Elveskevtar can you sign CLA and resolve conflicts? Really appreciated!

**Comment by morrme** [comment]
@tehKapa So this looks good on its own but some of this may conlflict with @jackcmeyer  's hooks migration. I don't have access to view/resolve conflicts but I suspect that may be what's going on.

**Comment by fox1t** [comment]
Is this PR stale?

**Pull request closed without merging**
