### PR TITLE
Added a calendar that displays appointments (WIP)

### LINKED ISSUE #760: Add calendar view to appointments
We need to add a calendar view.  This calendar view should support a weekly view and a daily view.
Like the appointment search (/appointments/search), you should be able to filter on:
Doctor
Type
Location

On the calendar the following items should display with a link to appointment details:

First Name
Last Name
Doctor to be seen

### PR DESCRIPTION
**Pull request by BogdanAlexandru**
Fixes #760

**Changes proposed in this pull request:**
- Bring in [ember-fullcalendar](https://www.npmjs.com/package/ember-fullcalendar);
- Display appointments in a new route within the calendar;
- Allow the user to get to an appointment's edit page via the calendar.

cc @HospitalRun/core-maintainers
- - -
This is still WIP. Stuff that still needs to be done:

1. Automated tests.
2. Extra query params to store the calendar's current settings (date and view type) when navigating to an appointment and back.
3. This comment in the calendar route: `// To cater for times like 0:00 - investigate.`
4. Write our own header to style the calendar controls so they look more like the rest of HR;
5. The pinned 3.1.1 jQuery dependency was an initial workaround to get things running - have to check that out again;
6. Anything else that comes up here.

Things that I don't like very much include the redundant first query for the model the calendar route performs. The idea there is a bit backwards, so I'm not sure how to avoid it. The model to load is indicated by the calendar control, but you need a loaded route to get the calendar control, so you always have two loads. When returning from an appointment, it will do the first redundant load, then reset the calendar to the passed in view config, then reload.

Throw all your critique my way 👍

### CODE REVIEW

**Comment by BogdanAlexandru** [comment]
As this progresses I'll try to get a live view of my branch going on some server somewhere. It's a fairly large addition and I feel screenshots/videos/gifs aren't that helpful for seeing how it works.

**Comment by jkleinsc** [comment]
@BogdanAlexandru thanks for the update!

**Comment by jkleinsc** [comment]
@BogdanAlexandru I need to move this feature along.  If you aren't working on it, I'd like to take what you have and continue working on it myself.

**Comment by BogdanAlexandru** [comment]
I'm unable to work right now and won't be for the near future. The calendar-view branch has all of my latest changes, nothing on local needs pushing.

Sorry for the late notice on this.

**Comment by jkleinsc** [comment]
Merging existing PR into calendar branch so I can continue the work that @BogdanAlexandru started.  Thanks @BogdanAlexandru for your efforts!

**Pull request merged**
