### PR TITLE
fix(2494): Incidents: Add the ability to edit incident details

### LINKED ISSUE #2494: Incidents: Add incident edit form
## 🚀 Feature Proposal

Add the ability to edit a reported incident.

## Motivation

One an incident has been reported, the system must provide a way to update it, to correct any mistakes or provide a progress update.

#### Incident Model

Add the following new fields to the incident model

```
reportedTo: string
```

#### Incident View Form

Make the following fields editable on the current view form: department, category, category item, description, incident reported to, patient impacted (introduced via #2493)

##### Footer 
- Add a new footer button "Update" which will save changes made by the user.

### PR DESCRIPTION
**Pull request by riiniii**
fix #2494

Fixes #2494.

Changes proposed in this pull request:

- merge code from master to current branch
- change useResolveIncident hook to useUpdateIncident
- in ViewIncidentDetails page, implement controlled inputs/forms with useState and useEffect, and make relevant fields editable: 
        1a. department
	1b. category
	1c. category item
	1d. description
	1e. incident reported to (*) - (to-do, need more info on whether this maps to another user or is just string field)
	1f. patient impacted
- make ViewIncidentDetails.test.tsx reflect that form should be editable
- make it so that patient field is always visible, with on view/update, allows user to update the patient field from previously null/empty/undeff to a new patient value
- add reportedTo
- 
to do: 
- add tests to search for update button

### CODE REVIEW

**Comment by tehKapa** [comment]
Hi @riiniii. Is this a WIP PR?

**Comment by riiniii** [comment]
> Hi @riiniii. Is this a WIP PR?

yes, it is. will add WIP next time!

**Comment by riiniii** [comment]
@tehKapa some of the tests are not passing due to enzyme module not found on git... do you know how this error can be fixed? assuming this has to do w github and not mines as its a test running remotely

**Comment by tehKapa** [comment]
@riiniii I've tested locally and it doesn't work on my Mac either. Could you please show me a screenshot of the tests that run on your PC?

**Comment by jameszheng405** [comment]
@riiniii Hi, can you sign the cla? Also, regarding the test failing, it might be that you are in a stale branch that hasn't completed the conversion to RTL. Perhaps you could run `git merge` and update this branch.

**Comment by riiniii** [comment]
> @riiniii Hi, can you sign the cla? Also, regarding the test failing, it might be that you are in a stale branch that hasn't completed the conversion to RTL. Perhaps you could run `git merge` and update this branch.

ok! shall try, ty!

**Comment by riiniii** [comment]
@jameszheng405 closing this pr in favor of #2689 where i cherry picked the relevant commits from here + tests pass.

**Pull request closed without merging**
