### PR TITLE
Inventory summary report

### PR DESCRIPTION
**Pull request by tangollama**
@jkleinsc, I think this is ready to go.

### CODE REVIEW

**Comment by jkleinsc** [comment]
@tangollama Can you remove the commented out console.logs?  Also, looks like there are some compile warnings you need to fix.  See:
https://travis-ci.org/HospitalRun/hospitalrun-frontend/builds/79578002

**Comment by tangollama** [comment]
Yes I candor the console logs. As for the warnings, I really wasn't sure how to address those but I'll give it a go. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by jkleinsc** [comment]
@tangollama the proper way to handle the errors about reject not being used were to use reject properly, not remove it completely.  Regardless, I am going to merge this pull request and fix the issue myself.

**Comment by tangollama** [comment]
Ok thx. I'm happy to get appropriate instruction on that. I couldn't seem to find a context where it worked properly. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by jkleinsc** [comment]
@tangollama see 73a01382101296bbdccdbd2b9d3d3f4cbab5a696 for how I updated the code to use reject. Basically the concept is we bubble up the errors and display an error message at the top level of the promise chain.

**Pull request merged**
