### PR TITLE
Improving french translations

### PR DESCRIPTION
**Pull request by Raul6469**
Fixes some translations in french and spanish and adds some new translations.

While going through french translations, I fixed mistakes that changed the original meaning of the string. For example, "noon" and "midnight" were inverted. Also the case for the `totalMontlyExpense` translation : it was translated as income. And finally, "confinement" was translated as childbirth. 

I fixed these errors, but I don't know if it's really a good idea, because it can be really disruptive for the french speaking users. What do you think?

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by atochef** [comment]
I would like to work on improving the Spanish translations as a project for my Software practicum at College of Charleston.
As a native spanish speaker with experience in the health care system, I think I could contribute to HospitalRun. I would appreciate it greatly if you agree to let me do this part.

**Comment by Raul6469** [comment]
Hello @atochef 

No problem, I understand : I can revert the spanish translations commit so you can do it if you want.

I was mainly focused on french translations, but as a spanish speaker, I also checked spanish translations to help me understand the string meaning when needed, and filled the empty translations as I was going.

**Comment by Raul6469** [comment]
Hi @stukalin, what's the current status of this PR?

**Comment by stukalin** [comment]
@Raul6469 it was accepted. I can't merge PRs myself, so let's bother @tangollama by mentioning him here :stuck_out_tongue:

**Pull request merged**
