### PR TITLE
Issue 673 - fix indentation

### LINKED ISSUE #673: enable block-indentation in .template-lintrc.js
We currently have many html indentation errors.

in order to prevent new commits to not have these errors we need to enable `block-indentation`.

To see errors:
1. Open `.template-lintrc.js` in your editor
2. set `block-indentation` to true 
3. ember build

you can fix errors and run `ember build` to see more at any point in time Please note if you don't fix all of them that is ok, open a pr with the ones you fixed omitting the change to `.template-lintrc.js`

### PR DESCRIPTION
**Pull request by jmabry111**
Fixes #673

**Changes proposed in this pull request:**
- Sorry this is such a big PR, but as the issue stated, there were many indentation issues.
- All build indentation errors corrected: `ember build` completes with no errors

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by jmabry111** [comment]
Not sure why the tests failed on travis... they all pass locally?

**Comment by billybonks** [comment]
@jmabry111, i tried to get travis to rebuild, but the button didn't seem to work. could you just add a commit run tests then remove it to rewrite history and force travis to rebuild

**Comment by billybonks** [comment]
there seems to be a new error now, caused by snyk. ill look into it

**Comment by jmabry111** [comment]
Awesome... looks like the tests passed that time 👍

**Comment by billybonks** [comment]
@jmabry111 thanks

**Pull request merged**
