### PR TITLE
Refactor defaultVisitTypes to use i18n

### PR DESCRIPTION
**Pull request by rodolfoghi**
- Refactor defaultVisitTypes to use i18n.
- Added some missing translations to pt-BR.

### CODE REVIEW

**Comment by jkleinsc** [comment]
@rodolfoghi thanks for the PR.  Unfortunately localizing visit types is complicated by the fact that there is logic in the system looking for specific visit types, namely the following:

- Admission
- Imaging
- Lab
- Pharmacy

I think the solution is to keep the statuses in the database as English but then to localize wherever  the status is displayed

Admission is referenced in the following files:
app/admin/lookup/controller.js
app/appointments/calendar/controller.js
app/appointments/edit/controller.js
app/appointments/edit/route.js
app/mixins/patient-notes.js
app/mixins/visit-types.js
app/models/appointment.js
app/patients/outpatient/controller.js
app/visits/edit/controller.js
app/visits/edit/route.js
tests/acceptance/admin-test.js

Imaging is referenced in the following file (calling addChildToVisit):
app/imaging/edit/controller.js

Lab is referenced in the following file (calling addChildToVisit):
app/labs/edit/controller.js

Pharmacy is reference in the following file (calling addChildToVisit):
app/medication/edit/controller.js

**Comment by tangollama** [comment]
@rodolfoghi are you interested in continuing forward with this PR? If so, great. If not, I'll close.

**Comment by tangollama** [comment]
@rodolfoghi reply back if you're intending to try to respond to the feedback on this PR, even if the timeline is extended. That's fine. It's volunteer work. I just don't want to leave this open if it's not going anywhere.

**Comment by rodolfoghi** [comment]
Yes, I intend to continue with this PR. Sorry for the delay to respond.

**Comment by rodolfoghi** [comment]
I've reversed the changes, because this i'll close this PR.

**Pull request closed without merging**
