### PR TITLE
added occupation to patient profil

### PR DESCRIPTION
**Pull request by lansanasylla**
**Changes proposed in this pull request:**

 i added the occupation field on the patient profil (that did not exist before) 

-

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by jglovier** [comment]
@lansanasylla thanks for the pull request. Please complete the body of the pull request per the template provided (i.e. list out a summary of what you are proposing in the pull request, and in the `Fixes # .` line please reference any relevant issues that this pull address. Thanks!

**Comment by jkleinsc** [comment]
@lansanasylla we would be happy to merge in this PR, but we would ask for a short description as to what you are adding in.  Also, your change doesn't look properly laid out as the columns are now unbalanced:
screen shot 2016-05-11 at 2 30 31 pm

**Comment by lansanasylla** [comment]
hello @jkleinsc and @jglovier, i added the occupation field on the patient profil (that did not exist before)  and now the colum are not unbalanced

**Comment by jkleinsc** [comment]
@lansanasylla that looks better, but I think the occupation field would be better suited to be after Place of Birth.

**Comment by lansanasylla** [comment]
ok @jkleinsc  i'm going to move it

**Pull request closed without merging**
