### PR TITLE
Added Analytics

### PR DESCRIPTION
**Pull request by cd2-public**
Initial addition of Analytics via google to app

### CODE REVIEW

**Comment by cd2-public** [comment]
probably... I can iterate on this and come back, tbh I get the same error, but realtime analytics shows my visits pinging to google analytics dashboard, so it works as-is, it's just ugly.

**Comment by jglovier** [comment]
I think we probably want to use [Event Tracking](https://developers.google.com/analytics/devguides/collection/analyticsjs/events) to get insights into where users are clicking in the UI.

**Comment by Lewiscowles1986** [comment]
already mentioned this, all clicks are registered by google analytics automatically

**Comment by turboMaCk** [comment]
At first you include analytics only in index.html not to tests/index.html. Also you have to define global var if you want to use this https://github.com/HospitalRun/hospitalrun-frontend/pull/229/files#diff-f3a289058604b2b069d07bb8e2cda60cR9

After all I do not think this is a good implementation.

1) What about using segment https://segment.com/?
2) I will rather define service for analytics stuff (something as a wrapper)

**Comment by Lewiscowles1986** [comment]
going to be integrating ember-metrics package

**Comment by turboMaCk** [comment]
looks like better solution

**Comment by jkleinsc** [comment]
I am closing this PR in favor of using ember-metrics.

**Pull request closed without merging**
