### PR TITLE
WIP - Add ability to create a patient when adding a related person that does not exist

### LINKED ISSUE #2106: Ability to create a patient when adding a related person that does not exist
## 🚀 Feature Proposal
When creating a Related Person, it assumes that the patient that you want to add as a related person already exists. If the related person does not exist, it is cumbersome to exit the related person modal and go create that patient, then come back to finally add the related person. 

Users would like the ability to have some sort of "quick add" that allows me to create a new patient without leaving the related person modal.

## Motivation
Be able to quickly add related persons that aren't currently existing patients.

### PR DESCRIPTION
**Pull request by JDarke**
Fixes #2106 .

**Changes proposed in this pull request:**

- Created 2 new components for Related Person tab (Dashboard > Patient > Related Person):  AddNewRelatedPanel (replaces AddNewRelatedModal), and CreateRelatedPersonPanel (adds New Patient creation functionality)

- Modified RelatedPerson tab to implement these new components as per user story here: https://github.com/HospitalRun/hospitalrun-frontend/issues/2106#issuecomment-641969597

Current Functionality:  
1. If no match found in AddNewRelatedPanel search field, Save button click reveals CreateRelatedPersonPanel
2. If Relationship Type field is left blank in AddNewRelatedPanel, filling in the matching field in CreateRelatedPersonPanel automatically copies the value to AddNewRelatedPanel, but will not overwrite an existing value (needs fixing)
3. CreateRelatedPersonPanel successfully creates new patient record if required fields are supplied
4. New patient must then still be added using the AddNewRelatedPanel.

Required functionality:
1. After dispatching the new patient creation action, the id of the new patient should be captured and used to dispatch an addRelatedPerson action on the existing patient, rather than having to do it manually as in point 4 above.
2. The Relationship Type field in AddNewRelatedPanel should take its value from Realtionship Type field in CreateRelatedPersonPanel, over-writing existing value if it exists.
3. The Given Name and Relationship Type fields in CreateRelatedPersonPanel should autopopulate from the Related Person and Relationship Type fields in AddNewRelatedPanel.  

Basically, the two Relationship Type fields should be synced, either in realtime or when either Save button is pressed, as should the respective Related Person and Given Name fields.  **If point 1 of the required functionality is achieved, then this only needs to happen in one direction, from AddNewRelatedPanel to CreateRelatedPersonPanel.**

I'm submitting the PR at this stage as while I can see some ways to achieve the goals, such as adding referral props to the patient model, but that starts to seem a little messy and I'd mainly like some feedback on the following:

1.  Is the overall structure of the feature viable / advisable so far, or do I need to back up a few steps and rethink it?  
2.  Is there a clean way to capture the id of the newly created patient after it is dispatched, without having to add entirely new functionality to the patient creation process?
3.  If not, is it more advisable to simply dispatch the new patient creator, then autopopulate the Related Person and Relationship fields in AddNewRelatedPanel from the values in the Given Name and Relationship fields in the CreateRelatedPersonPanel, and have the user manually confirm the final step there?

General tips and advice also welcome!

### CODE REVIEW

**Comment by JDarke** [comment]
@jackcmeyer  Thanks for that - makes sense, I'll get on it.

**Comment by JDarke** [comment]
Hey, Jack, sorry for the delay on this....had some deadlines to meet elsewhere.  Working on it now!

**Comment by tehKapa** [comment]
@JDarke need help?

**Comment by JDarke** [comment]
> @JDarke need help?

Thnaks, @tehKapa , that's much appreciated.  I may take you up on the offer in a few days, but I think I have a solution.  I've just been ridiculously busy over the past few weeks. 

If this issue is holding up progress elsewhere, just let me know and I'll pass it on to someone else, but I'd really like to finish this one if possible!

**Pull request closed without merging**
