### PR TITLE
add appveyor config

### PR DESCRIPTION
**Pull request by donaldwasserman**
This is another attempt to get appveyor working to test/deploy electron builds on windows.

### CODE REVIEW

**Comment by MatthewDorner** [comment]
I was playing with this as well, FYI I was able to get electron artifacts to build and make available the windows binaries on appveyor using this:

https://github.com/MatthewDorner/hospitalrun-frontend/blob/appveyor-test/appveyor.yml

Then I added some code for S3 deployment that I found, but I didn't have a S3 service to test with.

**Comment by MatthewDorner** [comment]
cool, if you want to use that script you'll need some of these other changes. Mainly the script in package.json and possibly also the electron-forge-config.js ones.

https://github.com/HospitalRun/hospitalrun-frontend/compare/master...MatthewDorner:appveyor-test

**Comment by donaldwasserman** [comment]
@MatthewDorner - so you disabled the tests from running in electron then? or are they running somehow through forge?

**Comment by MatthewDorner** [comment]
The electron tests run when it does "npm run-script electron-test". Do you mean having the electron tests be a separate job in appveyor like it is in Travis?

**Comment by MatthewDorner** [comment]
Gave this another try, all the errors are different now.

As usual I got it working on my PC and my Appveyor account https://ci.appveyor.com/project/MatthewDorner/hospitalrun-frontend but not this one. Looks like it's building Electron but failing on the `ember test`. I was having the same test failures when I was using VS 2015 Appveyor and it got fixed when I went to VS 2017 in the Appveyor project settings. Tried specifying the VS 2017 image in appveyor.yml here but it's still failing.

**Pull request closed without merging**
