### PR TITLE
fix(i18n): fixed typo of remission text

### LINKED ISSUE #2463: Add diagnosis form - fix typo in one of the statuses
## 🐛 Bug Report

There is a typo in remission on the list of statuses; it is spelt **remisison** instead of **remission**.

## To Reproduce

On https://staging.hospitalrun.io/
1. Login and go to patients, 
2. Select an existing patient to view or create a new one if no patients already exist, then view the patient
3. Click Add Diagnosis, this opens up the Diagnosis form; Click the status dropdown and notice remission is spelt incorrectly. 

image

## Expected behavior

Spellings should be correct. i.e. **remission** instead of  **remisison**.

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

### PR DESCRIPTION
**Pull request by Mani-07**
Fixes #2463 

**Changes proposed in this pull request:**

- fixed typo of "remission"

Attached screenshot
updated_typo

### CODE REVIEW

**Comment by tehKapa** [comment]
Hi @Mani-07, thank you for your submission! Please sign our CLA before we can accept your contribution.

**Comment by Mani-07** [comment]
@tehKapa  - I have signed in CLA. Could you approve m PR?

**Comment by Mani-07** [comment]
@tehKapa - I have signed in CLA. Can you Please approve my PR?

**Comment by tehKapa** [comment]
@Mani-07 Could you rebase your commit? This isn't a feature but a fix.

**Review by tehKapa — APPROVED** [review]

**Pull request merged**
