### PR TITLE
Use `qunit-dom` for DOM assertions

### PR DESCRIPTION
**Pull request by Turbo87**
see https://github.com/simplabs/qunit-dom

this will be the default way to do DOM assertions starting with Ember CLI 3.2

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by Turbo87** [comment]
hmm... I don't understand why those tests are failing. They seem entirely unrelated to the changes in this PR 🤔

**Comment by Turbo87** [comment]
@stukalin what's needed for this to get merged?

**Comment by stukalin** [comment]
@Turbo87 unfortunatelly I can't merge. We'll have to wait @tangollama or @jkleinsc

**Comment by tangollama** [comment]
I’ll make sure this happens tomorrow. Thx for the PR. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by Turbo87** [comment]
@tangollama awesome, thanks! make sure to also have a look at #1425, which should unblock another PR I've already queued up 😉

**Comment by tangollama** [comment]
Thank you again @Turbo87 for the PR!

**Pull request merged**
