### PR TITLE
Spanish localization

### PR DESCRIPTION
**Pull request by chibchombiano26**
Spanish es-CO colombia south america

Fixes #[replace brackets with the issue number that your pull request addresses].

**Changes proposed in this pull request:**
- [list out summary of changes here]
- [list out summary of changes here]
- [list out summary of changes here]
- [etc]

*Note: pull requests without proper descriptions may simply be closed without further discussion. We appreciate your contributions, but need to know what you are offering in clearly described format. Thanks! (you can delete this text)*

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by jkleinsc** [comment]
@chibchombiano26 is this still a work in progress?  It looks like some of the text has not been translated yet?  For example, I believe "Total Purchases Consumed" should be translated to "Las compras totales consumidas" or something similar.

**Comment by chibchombiano26** [comment]
Hi @jkleinsc, yeah you right there are some few missing translation because i need first navigate between pages to understand better what is this trying to say,. I am a native spanish speaking. In example, Total Purchases Consumed could be mean Total Purchases Consumed or inventario  restante. that is the reason because i left some translation on english. of course when i navigated all the app i am going to complete those translations.

**Comment by chibchombiano26** [comment]
your traslation comes from google translator ? and another question do you want wait while i finish all the translation? or do you think it is a good start for the spanish localization

**Comment by jkleinsc** [comment]
@chibchombiano26 my translation did come from google translator.  I think it is a good idea to wait until the whole file has been translated before merging it.

**Comment by chibchombiano26** [comment]
Ok no problem

**Comment by chibchombiano26** [comment]
hi @jkleinsc i improve my translations files, but i have a llitle problem i dont know how exclude this file c9-couch.js from the pull request without modify the .gitignorefile

Thanks

**Comment by jkleinsc** [comment]
@chibchombiano26 you can add c9-couch.js to the .gitignore

There also should be a way to have a local gitignore setup, but this file is ok to add to the .gitignore

**Comment by chibchombiano26** [comment]
ok... added... Could you please check if my last commit is ready to get included in your project?
Thanks so much

**Comment by jkleinsc** [comment]
@chibchombiano26 you need to change the gitignore for c9-couch.js to `c9-couch.js` instead of `/c9-couch.js` because right now it is not ignoring that file.  Other than that I think this PR is ready to merge.

**Comment by chibchombiano26** [comment]
done.

**Comment by chibchombiano26** [comment]
Done

**Comment by jkleinsc** [comment]
@chibchombiano26 thanks for the PR!  It looks good, so I am going to merge it now.

**Pull request merged**
