### PR TITLE
Bug: page refresh (hot reload) fix

### LINKED ISSUE #2201: App route goes to "/" after refresh
## 🐛 Bug Report
After page refresh app route goes to "/".
Also it slightly harms developer experience (impossible to use hot reload feature).

## To Reproduce
1. Go to any route except "/", for example "/patients/new".
2. Try to refresh a page

## Expected behavior
1. Route should stay same after page refreshing.

## Your Environment
- *node version*: 12.6.1
- *os*:  Linux

P.S. I want to help with solving this issue. I've already fixed it and I could make PR if you don't mind.

### PR DESCRIPTION
**Pull request by vault-developer**
Fixes #2201 

**Changes proposed in this pull request:**
- fix app route changing after page refresh

**Newly added dependencies with [Bundlephobia](https://bundlephobia.com/) links:**
- no new dependencies added

### CODE REVIEW

**Comment by tehKapa** [comment]
@vault-developer can you resolve the conflict? thanks!

**Comment by vault-developer** [comment]
@tehKapa done

**Comment by fox1t** [comment]
@vault-developer there are some conflicts again :(

**Comment by vault-developer** [comment]
@fox1t @tehKapa 
I merged all updates right before PR, and then today one more time.
How many times should I do it?

**Comment by tehKapa** [comment]
> @fox1t @tehKapa
> I merged all updates right before PR, and then today one more time.
> How many times should I do it?

depends on other PR. some PRs don't touch the same part of code, others do :(

**Pull request merged**
