### PR TITLE
Fix search bar text field

### PR DESCRIPTION
**Pull request by MatthewDorner**
Change in behavior was introduced in the fix for #1366: The text in the search bar used to get cleared if you 1) submitted a search or 2) moved to a different nav item. Now, the text remains in the search bar unless you clear it yourself.

Steps to reproduce:
- With current c68eaec code, perform a search and observe the text remains in the search field (top screenshot).
- Move to a different nav item and observe the text still stays there (bottom screenshot).
- Checkout commit 215c1fc from before #1366 fix and perform the same steps, observe the text is cleared in both cases (perform search, or move to different nav item).

search_screenshot

**Changes proposed in this pull request:**
- pass searchText property into the sidebar-nav component to restore the original behavior.

** note: I observed the code to clear the search text is inside the search() action. the only reason it gets cleared when you move to a different nav item is because every time you move to a different nav item after having entered search text, it performs your search before it transitions. I guess this is because it's running that search action any time you blur the text field. my code doesn't change anything about this, but I could look at making it so it only searches on enter or clicking the search button if you think that would be worthwhile.

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by MatthewDorner** [comment]
cool, I should be able to add that test.

**Comment by MatthewDorner** [comment]
Added the acceptance tests to the navigation-test.js file, does that seem like the right place for them? Also confirmed that tests fail if the line in application.hbs is removed, and pass once the line is added.

**Comment by stukalin** [comment]
@MatthewDorner your changes were approved but some tests fail on Travis. Could you please fix them?

**Comment by MatthewDorner** [comment]
oh, yeah. I see why it's failing now. strangely I didn't get those when I ran tests on my system. I will fix it.

**Comment by MatthewDorner** [comment]
Sorry about that, had to change the solution slightly, but I think it's better this way anyway.

**Comment by tangollama** [comment]
Thank you @MatthewDorner for the PR!

**Pull request merged**
