### PR TITLE
Better README.md

### PR DESCRIPTION
**Pull request by mathiasrw**
If you know very little about git/node/npm this description will be more helpful to people.

[Review on Reviewable](https://reviewable.io/reviews/hospitalrun/hospitalrun-frontend/215)

### CODE REVIEW

**Comment by jglovier** [comment]
Looking MUCH better - thanks @mathiasrw!! :metal: :zap: :heart:

carl-sagan-youre-awesome

:shipit:

**Comment by mathiasrw** [comment]
### Best Pull Request response ever !

_Dont konw about the failed checks... I have changed no code..._

**Comment by jglovier** [comment]
>Dont konw about the failed checks... I have changed no code...

Yeah, I think that's project wide. I'm seeing the same failure in other PRs, too. @jkleinsc any ideas what's going on there? I think it might be because the build is failing in Travis in general.

**Comment by jkleinsc** [comment]
Travis is failing because I missed something when I fixed deprecations for Ember 2.2.  I'm on it.

**Comment by jkleinsc** [comment]
Travis is not working properly and this PR has been merged.  Thanks for the PR @mathiasrw

**Comment by mathiasrw** [comment]
:+1:

**Pull request closed without merging**
