### PR TITLE
Adding ember-cli-content-security-policy with defaults for dev

### PR DESCRIPTION
**Pull request by pete-the-pete**
PR for #285

This adds the CSP without errors while working locally.

### CODE REVIEW

**Comment by jkleinsc** [comment]
@pete-the-pete I just ran your PR through tests, and I do see one CSP warning that I wonder if you can resolve:
[Report Only] Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAeCAYAAAAsEj5rAAAAUklEQ…EBEnMgMQ8S8+AqBIl6kKgHiXqQqAeJepBo/z38J/U0uAHlaBkBl9I4GwAAAABJRU5ErkJggg==' because it violates the following Content Security Policy directive: "img-src 'self'". 

This comes from pikaday.js which is the date picker we use.  

Other than that this PR looks like its good and solves the issues we were having previously.

**Comment by pete-the-pete** [comment]
sure, i'll take a look this evening, sorry I missed it.

**Comment by jkleinsc** [comment]
Fixes #285

**Comment by jkleinsc** [comment]
Thanks for the PR @pete-the-pete !

**Comment by pete-the-pete** [comment]
My pleasure, should #285 be closed?

**Comment by jkleinsc** [comment]
@pete-the-pete yes, it should be closed.  I thought I did close it, but it looks like I didn't

**Pull request closed without merging**
