### PR TITLE
test(login): improve test login screen

### LINKED ISSUE #2278: Improve test on Login.tsx
It's necessary to improve the testing of [Login.tsx](https://coveralls.io/builds/32646552/source?filename=src/login/Login.tsx) because it lowers the global percentage by a lot

### PR DESCRIPTION
**Pull request by rsousaj**
Fixes #2278 

- Added unit tests for Login Screen

### CODE REVIEW

**Comment by rsousaj** [comment]
Hi guys, sorry about the import's mess. It's my first contribution.
So, I tried to cancel the PR but I couldn't.

How can I procedure now ?

Thanks

**Comment by morrme** [comment]
> Hi guys, sorry about the import's mess. It's my first contribution.
> So, I tried to cancel the PR but I couldn't.
> 
> How can I procedure now ?
> 
> Thanks

Thank you for your contribution!

Are you able to edit the file from your branch?

**Comment by rsousaj** [comment]
> > Hi guys, sorry about the import's mess. It's my first contribution.
> > So, I tried to cancel the PR but I couldn't.
> > How can I procedure now ?
> > Thanks
> 
> @rsousaj
> Welcome and thank you for your contribution!
> 
> Are you able to edit the file from your branch?
> 
> If so you can continue to make changes and then `git commit` and `git push` again. This PR will automatically reflect any additional change you make.

Oh, that's awesome! I'll clean up my mess

**Comment by rsousaj** [comment]
I've tried to refactor the imports but look like I'm still messing around. The organized import is not being recognized as a change when I try to commit on git. I'm so sorry guys.

Maybe would be better if the PR being rejected and I try starting all over again

**Comment by morrme** [comment]
> I've tried to refactor the imports but look like I'm still messing around. The organized import is not being recognized as a change when I try to commit on git. I'm so sorry guys.
> 
> Maybe would be better if the PR being rejected and I try starting all over again

Can you tell us what you're trying to accomplish, or send a screenshot of the changes as they appear for you locally? 

Have you tried "staging" your changes (via `git add`) before committing?

**Comment by rsousaj** [comment]
> > I've tried to refactor the imports but look like I'm still messing around. The organized import is not being recognized as a change when I try to commit on git. I'm so sorry guys.
> > Maybe would be better if the PR being rejected and I try starting all over again
> 
> Can you tell us what you're trying to accomplish, or send a screenshot of the changes as they appear for you locally?
> 
> Have you tried "staging" your changes (via `git add`) before committing?

Oh, thank you so much. Really appreciate! Down below the screenshot after staging changes.

screenshot01

But after commit, it fails on "no-empty-commit" rule. Before, I need to admit that, I tried to cheat and also changed the Test Suite name but couldn't commit the right code.

**Comment by morrme** [comment]
@rsousaj Are you referring to the import order? This might be something that is changing based on the project standards. 
It looks like your code has passed all of the checks, including those for import order, so you may be ok 👍🏾

**Comment by rsousaj** [comment]
> @rsousaj Are you referring to the import order? This might be something that is changing based on the project standards.
> It looks like your code has passed all of the checks, including those for import order, so you may be ok 👍🏾

Yes, I was. Once more, tks a lot. Really happy to contribute.

**Comment by morrme** [comment]
> Yes, I was. Once more, tks a lot. Really happy to contribute.

We are happy to have you ! Feel free to join us in the Slack group as well: https://hospitalrun-slack.herokuapp.com/

**Comment by morrme** [comment]
@jackcmeyer Do you mind reviewing this one?

**Review by jackcmeyer — APPROVED** [review]

**Pull request merged**
