### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by billybonks**
OK so this is quite a few translation changes :)

- Refactored visits, to look a bit like the rest.
- translated components, parrtials, print.invoice
- fixed a few bugs

i have a note saying i must go through invoices aswell, would like to discuss my 2 refactor issues first.
 - https://github.com/HospitalRun/hospitalrun-frontend/issues/551
 - https://github.com/HospitalRun/hospitalrun-frontend/issues/547

### CODE REVIEW

**Comment by jkleinsc** [comment]
@billybonks -- one thing I realized is that invoices has some hospital specific information in it.  Specifically these labels:
+  print: {
 +    invoice: {
 +      hospital_name: 'TEBOW CURE HOSPITAL',
 +      hospital_address: 'J.P. Laurel Ave. corner Banawe St. Brgy Aquino Davao City, Philippines',
 +      hospital_contact: 'Telephone: (082) 300-5345    Email: info@tebowcure.org',
 +      hospital_footer: 'Certified Correct by: Leron L. Lehman- Executive Director',

I don't think we should add them to the translations file and I am thinking for now maybe we just completely remove this text from the input.  
Ideally this text is setup by an admin #419 was supposed to do this, but it never got completed.  

Invoicing needs more work in general, so I don't want to spend a lot of time working around this, particularly if we are going to refactor, so I am recommending we simply remove those fields from the print template and/or throw some generic text in for now.

Additionally, "billing.labels.phil_health" should be changed to a generic label, National Insurance

**Comment by billybonks** [comment]
@jkleinsc Updated based on your comments 👍 for now i removed all invoice changes will open a new pr for them

**Comment by jkleinsc** [comment]
@billybonks Does that mean this PR is ready to go?

**Comment by billybonks** [comment]
ye if you are happy with the code.

**Comment by jkleinsc** [comment]
Looks good to me.  I'll merge.

**Pull request merged**
