### PR TITLE
Address #569 - Contextual calls to action

### LINKED ISSUE #569: Make the Save (Add, Update) buttons always visible
The request is that any button to Save (Add or Update) would always be visible. Users would not need to scroll to the bottom of a page to find the button.    This could mean placing a second copy of the button at the top of the screen.   Request is to make this a standard across Hospital Run

### PR DESCRIPTION
**Pull request by James1x0**
I took a jab at #569. The difficult part is getting a nested controller's action to the parent controllers "section" context. I ended up just binding a context and dynamically setting additionalButtons. Lmk what you think; I'll be happy to continue iterations if needed. I've attached a screenshot.

Fixes #569.

**Changes proposed in this pull request:**
- Removes `new patient` button from `patients.edit` route
- Adds `cancel`, `update` buttons to `patients.edit` route

/cc @HospitalRun/core-maintainers

screenshot at oct 19 21-14-22

### CODE REVIEW

**Comment by jkleinsc** [comment]
@James1x0 thanks for the PR!  It seems that with this PR you are working upstream against the current architecture and I am wondering/thinking what this issue really needs is a refactoring of the "section" as #569 is addressed for the app as a whole, not just patients.

**Comment by James1x0** [comment]
@jkleinsc I'm thinking the issue kind of morphed into a different spec, see https://github.com/HospitalRun/hospitalrun-frontend/pull/656#issuecomment-252362375

But I wouldn't have anything against attempting a slight refactor of the section to account for this.

**Comment by jkleinsc** [comment]
@James1x0 I believe even with that comment the issue is looking for a change across the app or maybe I misunderstand your comment?

**Comment by James1x0** [comment]
@jkleinsc I'm probably reading it at face value. Summarizing, @jglovier suggested we replace the button up top in patients and then an overall style adjustment would follow. I'm making the change utilizing the section APIs. Maybe there should be a WIP PR? Thoughts?

**Comment by jkleinsc** [comment]
@James1x0 -- Yeah... the more I think about it, I think the issue needs clearer requirements/architectural direction before a PR.

**Comment by jkleinsc** [comment]
@James1x0 I am closing this issue because I've come to the conclusion that this issue needs further definition/architectural oversight before a solution can be applied.  See this comment for more details: https://github.com/HospitalRun/hospitalrun-frontend/issues/569#issuecomment-255200000

**Pull request closed without merging**
