### PR TITLE
Incident reporting 1.0

### PR DESCRIPTION
**Pull request by bininbhasi**
Please considering this pull request for adding the feature of incident-reporting to Hospitalrun.

incident-reporting-1.0 branch has been merged with Hospitalrun/master and all merge conflicts have been resolved.

### CODE REVIEW

**Comment by jkleinsc** [comment]
@jglovier at some point we should have you review the UI for this feature.  I think we may need to improve/refine what is already there.

**Comment by jglovier** [comment]
>@jglovier at some point we should have you review the UI for this feature. I think we may need to improve/refine what is already there.

@bininbhasi can you please include screenshots of the UI as it currently is in your changes?

**Comment by jglovier** [comment]
image

Also, this is a SUPER big PR with a ton of changes. Is there any way to break it down into smaller bits?

**Comment by jkleinsc** [comment]
@jglovier I am going to merge this PR manually because most of those changes don't need to come through.  I think @bininbhasi had issues rebasing.

**Comment by jglovier** [comment]
@jkleinsc :+1:

**Comment by jkleinsc** [comment]
Closing this PR in favor of a new one from this branch: https://github.com/HospitalRun/hospitalrun-frontend/tree/incident-reporting

**Pull request closed without merging**
