### PR TITLE
bump ember-sinon-qunit, disable package-lock.json

### LINKED ISSUE #1413: bump ember-sinon-qunit to latest
~~I'm going to fix the tests failing here: https://github.com/HospitalRun/hospitalrun-frontend/pull/1314~~
I had thought these tests still failed, but they seem to have been fixed. Bumping the dependency anyway to remove the ember-cli-babel deprecation warning when running ember build related commands.
**Expected behavior:**
All tests should pass.
**Actual behavior:**
A few tests fail. Such as:
https://travis-ci.org/HospitalRun/hospitalrun-frontend/jobs/340892498#L8126
**Steps to reproduce:**

**Screenshots (if applicable):**

**OS and Browser:**

### PR DESCRIPTION
**Pull request by efx**
Fixes #1413. This would also allow PR #1314 to be closed. Those test failures no longer fail on master.

**Changes proposed in this pull request:**
- bump ember-sinon-qunit to latest

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by efx** [comment]
I'm developing locally with npm@5.7.1 which could explain why the package-lock.json is so giant. Depending on what version of npm originally generated that lockfile, the lock algorithm has changed substantially and so can lead to churn. If this is a problem I can update with a new lockfile generated by the appropriate version of npm.

**Comment by stukalin** [comment]
@efx well this lock file problem.... The thing is that no one really uses it and our greenkeeper is not configured to update it which always brings conflict. Plus this 2 versions of the lock file add a bit of headache. I tried to add the lock file and then I removed it from the repo in the favor of yarn.lock which works more clear as to me. You might wanna have a look at our conversation in #1370 btw.

**Comment by efx** [comment]
gotcha @stukalin. So should I revert the lock file change and keep the version bump? Also, we could add an .npmrc file to the project root to disable lockfile generation if you want.

**Comment by stukalin** [comment]
@efx yes, please. I'll approve your PR meanwhile.

**Pull request merged**
