### PR TITLE
Adding the notes and patient history

### PR DESCRIPTION
**Pull request by tangollama**
Addresses issues #32 and #239

### CODE REVIEW

**Comment by jglovier** [comment]
its-happening-ron-paul

**Comment by jglovier** [comment]
Obligatory pull request UI snapshot:

screen shot 2016-03-23 at 9 13 27 am

**Comment by jglovier** [comment]
FYI the white space between the `+ New Note` button and the actual notes is killing me too, but it's symptomatic if a larger issue with how the markup is structured for content panels and default bootstrap styles which I should really address in a separate branch after this PR because it's going to touch a lot more than just this feature.

**Comment by tangollama** [comment]
@jkleinsc can you review and either merge or complain about something I didn't do yet?

**Comment by jkleinsc** [comment]
@tangollama unless I am missing something, it looks like your acceptance test doesn't really test the functionality of notes.  It should test crud operations on notes, not just test that the modal shows up.

**Comment by tangollama** [comment]
@jkleinsc I've expanded the test suite, addressed several translation issues (including injecting the i18n service into the model), and found and fixed a new bugs along the way. I think this is ready to go. The big question is how we can run the node script for updates. Do we need a release note process?

**Comment by tangollama** [comment]
Boom! @jkleinsc: MERGE. THAT. BRANCH!
http://i.imgur.com/nfo24RT.gif

**Comment by jglovier** [comment]
LOL well played gif @tangollama. 👏  😆 

PS: to put your gifs inline, just use the markdown image syntax: `name`. I went ahead and edited it for you. :wink:

**Comment by jkleinsc** [comment]
@tangollama settle down... its not like I'm busy with something else right now! LOL!
I'm not thrilled with the UI on the "behalf of" input, but if @jglovier is ok, I guess I'm ok with it, but I don't like the undefined in the background either (undefined on behalf of test).
screen shot 2016-03-28 at 4 14 58 pm

**Comment by tangollama** [comment]
Cool. As always, I'm open to instruction and recommendations. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by jglovier** [comment]
>I'm not thrilled with the UI on the "behalf of" input, but if @jglovier is ok, I guess I'm ok with it, but I don't like the undefined in the background either (undefined on behalf of test).

Oooo yeah, I didn't see that. @jkleinsc thanks for the screenshot (ALWAYS BE SCREENSHOTING :wink:)

That definitely needs some help, although we could take one of two approaches here.
1. punt on styling that as it's an issue with modal styling in general and fix in a new branch
2. add the fixes for modal styling to this branch and knock it out here

I'm open to either. @tangollama which would you prefer?

**Comment by tangollama** [comment]
@jglovier @jkleinsc I fixed the styling issue and the "undefined" text in the background last night. Behold!!

screen shot 2016-03-29 at 6 58 52 am

**Comment by jglovier** [comment]
@tangollama awesome! I'd call that Good Enough™ for this branch. I'll address modal styling overall in a new PR.

:shipit:

**Comment by jkleinsc** [comment]
Looks good @tangollama.  I am going to merge this PR in

**Comment by jglovier** [comment]
@jkleinsc FYI when you merge a request that way the contributor never gets credit for the contributions as they all become your commits.

**Comment by jkleinsc** [comment]
@jglovier I do this for PRs that have lots of commits because I don't want to bring all those commit messages over.  I guess we could ask contributors to squash the commits on their end and then we could just merge the PR.  If you have other thoughts on how we can better do this, I'm all ears.

Actually I would love a Github feature where I can merge a PR and squash the commits into one commit that credits the author!  That would make me 😀😀😀😀😀!

**Comment by jglovier** [comment]
>Actually I would love a Github feature where I can merge a PR and squash the commits into one commit that credits the author! That would make me 😀😀😀😀😀!

@jkleinsc ask an ye shall receive: https://github.com/blog/2141-squash-your-commits 😄

**Comment by jkleinsc** [comment]
@jglovier I think I shall do a happy dance: My Reaction

**Pull request closed without merging**
