### PR TITLE
Update Translation keys to JavaScript convention

### PR DESCRIPTION
**Pull request by TheBanditDave**
Fixes:
- user #575
- admin #576
- navigation #574
- labels #577
- messages #578
- buttons #579
- login #580

**Changes proposed in this pull request:**
- The start of changing Translation keys from _ standard to camel case to work with JavaScript convention.

*Note: @billybonks asked  me to submit a PR with what I had so far.*

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by jkleinsc** [comment]
Thanks for the PR @TheBanditDave !  It looks like according to the tests some of the translation labels are missing, so I assume you are still working on this one?

**Comment by TheBanditDave** [comment]
Hello @jkleinsc, your welcome! I am still working on it, I am planning to work on it today when I get home from work.

**Comment by jkleinsc** [comment]
@TheBanditDave is this PR ready to go now?  Let me know if/when you are done.  Thanks!

**Comment by billybonks** [comment]
If it's not then it's an untested part of the app

**Comment by TheBanditDave** [comment]
@jkleinsc I just pushed up the last changes for this PR. It was passing all the tests on my local environment. If there is any changes I need to make please let me know.

**Comment by jkleinsc** [comment]
@TheBanditDave looks good to me!  Thanks for working through this PR.  I'll merge it in.

**Pull request merged**
