### PR TITLE
fix: reset lab state when navigation from lab form

### LINKED ISSUE #2260: Previous errors are showing up in lab request screen
## 🐛 Bug Report
When creating a new lab request, if I request lab and it fails the validation and provides error feedback to the user, and then leave the page, and then come back, the previous errors are still on the page. 

## To Reproduce
1. Navigate to new lab request
2. Click the save button
3. see the validation errors
4. navigate to anywhere else in the system
5. navigate back to the new lab request screen
6. see that the errors are still present. 

## Expected behavior
The errors should no longer show when I navigate back to the lab request page.

### PR DESCRIPTION
**Pull request by Tomastomaslol**
Fixes #2260.

**Changes proposed in this pull request:**

- Added new action `resetLab` in `lab-slice.ts`
- Invoke `resetLab` when `newLabReuqest` is rendered

**No new dependencies added dependencies**

### CODE REVIEW

**Comment by tehKapa** [comment]
Hi @Tomastomaslol, can you sign our CLA before we can accept your PR? Thanks!

**Comment by Tomastomaslol** [comment]
Hi @tehKapa and thanks for looking at my pull request. I normally don't use GitHub so I had to amend my commit to match my Github account after accepting the CLA.  I'm not sure if that made the label confused. However, it looks like CLA check has passed in the list of checks. Should this be sufficient?

Otherwise, I can try to reopen the pull request.

**Comment by tehKapa** [comment]
That might be enough for me. @fox1t?

**Comment by jackcmeyer** [comment]
@Tomastomaslol I think we try and reopen the PR. I can see all the commits are associated with our account, so I think the bot may be confused.

**Comment by Tomastomaslol** [comment]
Reopened: https://github.com/HospitalRun/hospitalrun-frontend/pull/2268

**Pull request closed without merging**
