### PR TITLE
fix(patient): ensure new patient models always have a visits array

### PR DESCRIPTION
**Pull request by chadian**
I was following along the script in #2364:
> For a given patient, Jane Doe, on a given Lab for this patient, a user adds Note 1...

Adding a lab for a new patient without visits causes the new lab to throw since `visits` is undefined in [`patient.visits.map`](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/src/labs/requests/NewLabRequest.tsx#L54). The `Patient` type defines the `visits` array as being non-null ([`visits: Visit[]`](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/src/shared/model/Patient.ts#L28)) so it's important to ensure that an empty array exists to avoid these sort of runtime errors.

**Changes proposed in this pull request:**
- ensure patients always have a visits array (empty array when no visit exists yet)

### CODE REVIEW

**Review by tehKapa — APPROVED** [review]

**Review by blestab — APPROVED** [review]
Thanks @chadian , code working as expected.

image

vs staging (without this code) where there is no visits:[]

image

**Comment by chadian** [comment]
@blestab Can you do me a favour and remove the `in progress` label? Thanks!

**Comment by baoqchau** [comment]
@tehKapa Can this PR be merged? It has been approved

**Comment by chadian** [comment]
@blestab @tehKapa can this be merged?

**Review by tehKapa — APPROVED** [review]

**Pull request merged**
