### PR TITLE
feat(view patient): add 'edit' icon to Edit button

### LINKED ISSUE #1765: Edit patient details
## Scenario
**AS**

A user with write access to patients

**I WANT**

The ability to edit patient details

**SO THAT**

I can have more accurate patient information or change the patient information when needed.

## Acceptance Criteria
**GIVEN**

An existing patient and a user with write access to the patient

**WHEN**

I click the edit button the on patients page

**THEN**

The fields become editable

AND 

a save and cancel button toolbar appear at the bottom of the screen

AND 

when I click the button, then the updated patient details are persisted

AND

I get a success message saying I have successfully updated the patient details.

## Related Issues
HospitalRun/hospitalrun-frontend#1671

### PR DESCRIPTION
**Pull request by MatthewDorner**
Fixes #1765 

- Add 'edit' pencil icon to "Edit" button on View Patient component.

### CODE REVIEW

**Comment by MatthewDorner** [comment]
These test failures are confusing to me. One is failing due to 'document update conflict' and another one is failing because the storybook (?) part of the test script failed. But I don't even see storybook in the other test runs that passed. Have we still been having test problems? I just looked at GitHub actions on master branch and it looks like most are passing...

**Comment by tehKapa** [comment]
@MatthewDorner storybook check fails due to my error. I corrected github action conf file this morning

**Comment by MatthewDorner** [comment]
Yeah, I guessed the storybook thing was just added by mistake. Otherwise it looks like it's failing on Windows and the failure (on this and pretty much all the CI runs) is related to the tests that use PouchDB. Though I have seen those "document update conflict" errors a few times on my Linux environment, lately everything's been passing for me locally.

**Comment by tehKapa** [comment]
@HospitalRun/core-maintainers any of you guys got windows?

**Comment by MatthewDorner** [comment]
I can play around with it on a VM when I get some time. It's not just this PR, though, seems to have started failing this way on all the CI runs a few days ago...

**Comment by jackcmeyer** [comment]
@tehKapa I have a windows machine and I am unable to reproduce.

**Pull request merged**
