### PR TITLE
making the cancel update button always visible

### LINKED ISSUE #569: Make the Save (Add, Update) buttons always visible
The request is that any button to Save (Add or Update) would always be visible. Users would not need to scroll to the bottom of a page to find the button.    This could mean placing a second copy of the button at the top of the screen.   Request is to make this a standard across Hospital Run

### PR DESCRIPTION
**Pull request by ShadabQ**
Fixes #569 make the save update button always visible.

**Changes proposed in this pull request:**
- make the footer-panel on /app/templates/components/edit-panel.hbs on the top.
- make its style as position:fixed.

cc @HospitalRun/core-maintainers @mnorbeck @tangollama @jglovier 
********************************************************************************************
<div class="panel panel-primary">
  
  <div class="panel-footer" style="position:fixed;">
    {{#unless editPanelProps.hideCancelButton}}
      {{#if editPanelProps.cancelButtonText}}
        <button class="btn btn-default warning" {{action 'cancel'}}>{{editPanelProps.cancelButtonText}}</button>
      {{else}}
        <button class="btn btn-default warning" {{action 'cancel'}}>{{t 'buttons.cancel'}}</button>
      {{/if}}
    {{/unless}}
    {{#if editPanelProps.showUpdateButton}}
      {{#if editPanelProps.disabledAction}}
        <button class="btn btn-primary on-white disabled-btn" {{action 'disabledAction'}}>{{editPanelProps.updateButtonText}}</button>
      {{else}}
        <button class="btn btn-primary on-white" {{action 'updateButtonAction'}} disabled={{editPanelProps.isUpdateDisabled}}>
          {{editPanelProps.updateButtonText}}
        </button>
      {{/if}}
    {{/if}}
    {{#each editPanelProps.additionalButtons as |button|}}
      <button class="{{button.class}}" {{action 'fireButtonAction' button.buttonAction}}>
        {{#if button.buttonIcon}}
          <span class="{{button.buttonIcon}}"></span>
        {{/if}}
        {{button.buttonText}}
      </button>
    {{/each}}
  </div>
  <div class="panel-body">
    {{yield}}
  </div>
</div>

### CODE REVIEW

**Comment by ShadabQ** [comment]
I have given the preview in the issue page but still ,I paste it here.

https://cloud.githubusercontent.com/assets/5912349/17195358/d98ceeee-547a-11e6-9536-2c7d40a27e34.png

**Comment by jkleinsc** [comment]
@ShadabQ when I test this, I don't see the same as your screenshot:
screen shot 2016-09-28 at 2 27 27 pm

I think we need to do more than just move the footer to be at the top of the screen.  @jglovier can you weigh in on this?

**Comment by ShadabQ** [comment]
Oh sorry,I missed the styles,i have updated it.

**Comment by jglovier** [comment]
I think the best path forward here is to leave the footer where it belongs (at the bottom), and just replace the new patient button in the header with the add/cancel buttons. It's going to need a bit more style help than that, but that's a good solution for now and I can jump in and address the overall header approach later. I'm thinking that should probably be fixed position anyway if we want to really keep it always visible.

**Comment by jkleinsc** [comment]
@ShadabQ I am closing this issue because I've come to the conclusion that this issue needs further definition/architectural oversight before a solution can be applied.  See this comment for more details: https://github.com/HospitalRun/hospitalrun-frontend/issues/569#issuecomment-255200000

**Pull request closed without merging**
