### PR TITLE
fix(incidents): running Incidents.test.tsx

### LINKED ISSUE #2453: Fix warning during Incidents.test.tsx
# 🐛 Bug Report
When running `Incidents.test.tsx`, there is a console error during the tests. 

```
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
          at module.exports (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
          at HTMLCanvasElementImpl.getContext (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
          at HTMLCanvasElement.getContext (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:50:45)
          at Object.acquireContext (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/chart.js/dist/Chart.js:7769:49)
          at Chart.construct (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/chart.js/dist/Chart.js:9324:26)
          at new Chart (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/chart.js/dist/Chart.js:9311:7)
          at LineGraph.componentDidMount (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/@hospitalrun/components/src/components/Graph/LineGraph.tsx:89:18)
          at commitLifeCycles (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/react-dom/cjs/react-dom.development.js:19814:22)
          at commitLayoutEffects (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/react-dom/cjs/react-dom.development.js:22803:7)
          at HTMLUnknownElement.callCallback (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/react-dom/cjs/react-dom.development.js:188:14) undefined
    console.error node_modules/chart.js/dist/Chart.js:9369
      Failed to create chart: can't acquire context from the given item

```

## To Reproduce
`npm test Incidents.test.tsx`

## Expected behavior
No warning should appear.

### PR DESCRIPTION
**Pull request by ho1234c**
Fixes #2453 

**Changes proposed in this pull request:**

- Add plugin to jest for mocking canvas 

**Newly added dependencies with [Bundlephobia](https://bundlephobia.com/) links:**

- https://bundlephobia.com/result?p=jest-canvas-mock@2.3.0

### CODE REVIEW

**Comment by tehKapa** [comment]
Hi @ho1234c, please sign our Contributor License Agreement

**Review by tehKapa — DISMISSED** [review]

**Comment by tehKapa** [comment]
@jackcmeyer seems to work. only thing.. I don't know if it's the only way to solve the issue.

**Comment by ho1234c** [comment]
Hi @tehKapa

https://github.com/HospitalRun/hospitalrun-frontend/pull/2455#issuecomment-716618699
I signed it. but I don't know why jsf-clabot still show not signed yet badge.
email used to sign is same as the email in github account.
maybe need few hours to verify?

**Comment by ho1234c** [comment]
https://github.com/HospitalRun/hospitalrun-frontend/pull/2455#issuecomment-716895687

It just author in commit was different.
pr was sent again after modification.

**Comment by tehKapa** [comment]
@ho1234c can you make a rebase or create a new PR?

**Comment by ho1234c** [comment]
@tehKapa done. I rebase this branch onto master.

**Comment by tehKapa** [comment]
@ho1234c doesn't seem to have worked :/

**Review by jackcmeyer — APPROVED** [review]

**Pull request merged**
