### PR TITLE
Select refactor

### PR DESCRIPTION
**Pull request by cynthiachen7**
Fixes HospitalRun#2101.

Changes proposed in this pull request:

- Replaced SelectWithLabelFormGroup component with Select and Label components in each appearance.
- Created a new component with the Option interface in SelectWithLabelFormGroup called SelectOption.
- Deleted SelectWithLabelFormGroup component and its corresponding test file.

### CODE REVIEW

**Comment by tehKapa** [comment]
@DrewGregory can you sign the CLA? Thanks!

**Review by DrewGregory — APPROVED** [review]
Looks great @cynthiachen7 !

**Comment by tehKapa** [comment]
@cynthiachen7 can update your branch with hr master?

**Comment by DrewGregory** [comment]
@tehKapa I updated branch.

**Pull request merged**
